echo "# project_recipes" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M test
git remote add origin https://github.com/rlb711/project_recipes.git
git push -u origin test
